services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/drizzle/0000_wise_shen.sql:/docker-entrypoint-initdb.d/0000_wise_shen.sql

volumes:
  db_data:
